"""empty message

Revision ID: 3bc95a63a5f7
Revises: cd12b2da66ce
Create Date: 2020-03-15 04:41:38.185837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc95a63a5f7'
down_revision = 'cd12b2da66ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('biography', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'biography')
    # ### end Alembic commands ###
